### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by btakashi**
Fix spelling mistakes, minor grammatical errors and improve clarity.

### CODE REVIEW

**Comment by seratch** [comment]
Embarrassing :sweat_smile:  Thank you so much! :+1:

**Comment by btakashi** [comment]
My pleasure!

**Comment by btakashi** [comment]
BTW, what's the relationship between this file and team-rules.md? Maybe team-rules.md should be merged w/ this file or deleted?

**Comment by seratch** [comment]
> team-rules.md

Although its title is a bit confusing but it is the guide for scalikejdbc org members that have permission to merge pull requests and release libs onto sonatype/maven central repository. It should be corrected too :cry:

**Pull request merged**
