### PR TITLE
use scalafmt instead of scalariform

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Review by seratch — APPROVED** [review]
This brings overwhelming amount of changes... but this makes sense as the last release of sbt-scalariform is back in 2019 and there is no update in their github repo after that.

**Comment by seratch** [comment]
Once the builds pass, please feel free to merge the change (or I will do it later on). Although I just released 4.0.0-RC1 a few minutes ago, I'm happy to have more RCs as necessary. As long as we don't have feature changes and no bug reports, we don't need to have more RCs before v4.0.0 release, though.

**Comment by seratch** [comment]
Interesting. The format detection fails on Windows OS.

**Comment by xuwei-k** [comment]
> Interesting. The format detection fails on Windows OS.

😭  I'll fix

**Pull request merged**
