### PR TITLE
[#1064] Generalize localTx with a higher kind to support IO monads

### PR DESCRIPTION
**Pull request by christobill**
@seratch the PR I mentionned in https://github.com/scalikejdbc/scalikejdbc/issues/1064#issuecomment-565864809

### CODE REVIEW

**Comment by seratch** [comment]
@christobill 
Thanks for making this revised pull request quickly!
The change looks good to me but I would like @xuwei-k to take a look, just in case.

**Comment by xuwei-k** [comment]
Hmmm, I think we should add another variant `localTx` without default `TxBoundary` implicit parameter? 🤔 

```diff
-  def localTx[A](execution: DBSession => A)(implicit boundary: TxBoundary[A] = defaultTxBoundary[A]): A = {
+  def someAnotherlocalTxWithoutDefaultArg[A](execution: DBSession => A)(implicit boundary: TxBoundary[A]): A = {
```

`fLocalTx[F[_], A]` doesn't make sense to me. (maybe higher kind parameter unnecessary)

**Comment by seratch** [comment]
@christobill It seems that we don't need this change as the way to use IO monads in a different way is now described here. Can I close this PR and the corresponding issue?
https://github.com/scalikejdbc/scalikejdbc.github.io/issues/87

**Comment by christobill** [comment]
@seratch can I just add the IO monads example in the tests? Either in this PR or in another one?
It could be valuable for further testing (for the `readOnly` on IO monads problem)

**Comment by seratch** [comment]
@christobill 
>can I just add the IO monads example in the tests?

This is a good idea. You don't need to create another PR for it. Could you update this PR?

**Comment by christobill** [comment]
@seratch I have updated the PR :)

**Pull request merged**
