### PR TITLE
Handled exceptions on commit(), rollback() and close()

### PR DESCRIPTION
**Pull request by tkawachi**
It's not tested yet. What's the best way to test it?

### CODE REVIEW

**Comment by tkawachi** [comment]
Now, TxBoundary for Try and Future doesn't throw an exception when commit(), rollback() or onClose() throws exceptions.

**Comment by seratch** [comment]
Great work. I just make some changes on your branch (renaming private methods/args, add some comments). If you prefer my changes, please merge them and then squash the commits into one.

**Comment by seratch** [comment]
https://github.com/seratch/scalikejdbc/commit/906d8823d2c7c7a5bcfbe96f10838b046da70317

**Comment by tkawachi** [comment]
melted into one commit

**Comment by seratch** [comment]
:+1:

**Pull request merged**
