### PR TITLE
Make toMap extractor timezone-wired

### PR DESCRIPTION
**Pull request by takayahilton**

### CODE REVIEW

**Comment by seratch** [comment]
Your change doesn't compile. Also, I haven't understood what your intention in this PR is yet. It looks an unnecessary change to me.

**Comment by takayahilton** [comment]
when 
```scala
withSQL {
 selectFrom(table as t)
}.map(rs => rs.getTimestamp("colum")).apply()
```
Time zone is converted. but
```scala
withSQL {
 selectFrom(table as t)
}.map(_.toMap).apply() 
```
Time zone is not converted.
This was an unexpected behavior for me.

**Comment by seratch** [comment]
I understand. I'm fine to improve the library to handle the case properly. Could you write some tests to make sure if your changes work as expected?

**Comment by seratch** [comment]
Thanks.

**Pull request merged**
