### PR TITLE
Add notBetween DSL

### PR DESCRIPTION
**Pull request by kobtea**
Add an interface for `not between` clause.

```scala
scala> sqls"".notBetween(sqls"user_id", 1, 10)
res0: scalikejdbc.interpolation.SQLSyntax = SQLSyntax(value:  user_id not between ? and ?, parameters: List(1, 10))
```

### CODE REVIEW

**Comment by seratch** [comment]
Thank you for your pull request. ScalikeJDBC build checks binary compatibility by using [MiMa](https://github.com/typesafehub/migration-manager/wiki/Sbt-plugin). Breaking existing APIs are not allowed but adding new methods are allowed. Please add exclusions for this change [here](https://github.com/scalikejdbc/scalikejdbc/blob/2.2.2/project/Build.scala#L26-L95) as below: 

```scala
// since 2.2.3
exclude[MissingMethodProblem]("scalikejdbc.QueryDSLFeature#ConditionSQLBuilder.notBetween"),
...
```

**Comment by kobtea** [comment]
I appreciate your help. Added a filter rule.

**Comment by seratch** [comment]
Please squash comits into one. 
(e.g.) doing git rebase -i HEAD〜2 and git push -f

**Comment by kobtea** [comment]
Re-added a filter rule at the end!

**Comment by seratch** [comment]
LGTM but this PR still has two commits. Please squash them again. https://github.com/scalikejdbc/scalikejdbc/pull/353/commits

**Comment by kobtea** [comment]
I see. Combine my whole commits into one.

**Comment by xuwei-k** [comment]
:+1:

**Pull request merged**
