### PR TITLE
SQLToCollection and DBSession#collection

### PR DESCRIPTION
**Pull request by gakuzzzz**
## TODO

* [x] setting mima compatibility check
* [x] implements one-to-x API
* [x] add tests

### CODE REVIEW

**Comment by gakuzzzz** [comment]
Would you review this? @seratch @xuwei-k

**Comment by xuwei-k** [comment]
squashed and code generator version (depends on #361)
https://github.com/xuwei-k/scalikejdbc/commit/3597cd2a534680352a7

**Comment by seratch** [comment]
Amazing. 

@gakuzzzz 
How about merging #361 first and @xuwei-k's one as another pull request next? If there are no objections today(JST), we'll go with that.

**Comment by gakuzzzz** [comment]
It's a nice plan merging #361 first and @xuwei-k's one as another pull request next.
I hate boilerplate :)

**Comment by seratch** [comment]
This pull request can be closed now.

@xuwei-k 
Could you create a pull request with your 'generate-gakuzzzz' branch when you have time?

**Comment by xuwei-k** [comment]
https://github.com/scalikejdbc/scalikejdbc/pull/362

**Pull request closed without merging**
