### PR TITLE
boilerplate is hard. let's generate code.

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by seratch** [comment]
This is pretty nice.

**Comment by seratch** [comment]
I'm not sure we should add 3-9 code to .gitignore. What do you think?

**Comment by xuwei-k** [comment]
> we should add 3-9 code to .gitignore

I think it is not necessary because there is [this line](https://github.com/scalikejdbc/scalikejdbc/blob/13e29ea250faca6c2c2dc0ce2352f264192d117d/.gitignore#L34)

**Comment by seratch** [comment]
I see. Thanks.

**Pull request merged**
