### PR TITLE
Fix generation error of tables with the same table name belong to different catalogs/schemas

### LINKED ISSUE #2126: scalikejdbc-mapper-generator  generates extra fields
```sql
CREATE TABLE users (
    user_id INT AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(100) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20),
    address VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

use  ` sbt "scalikejdbcGen users" `

```scala
case class Users(
  user: Option[String] = None,
  currentConnections: Long,
  totalConnections: Long,
  maxSessionControlledMemory: Long,
  maxSessionTotalMemory: Long,
  userId: Int,
  username: String,
  password: String,
  fullName: String,
  email: String,
  phoneNumber: Option[String] = None,
  address: Option[String] = None,
  createdAt: Option[ZonedDateTime] = None,
  updatedAt: Option[ZonedDateTime] = None) {

  def save()(implicit session: DBSession = Users.autoSession): Users = Users.save(this)(session)

  def destroy()(implicit session: DBSession = Users.autoSession): Int = Users.destroy(this)(session)

}
```
there are some extra fields

image

### PR DESCRIPTION
**Pull request by laglangyue**
## motivation
close #2126 
most databse use catalog.schema.table to locate the table.
And now the catalog is allways null. and listAllTables only return Seq(tableName)，it will cause unable to filter table correctly.
## how to
add catalog to scalikejdbc.mapper.Model#table
and scalikejdbc.mapper.Model#listAllTables show return the Seq(catalogName, tableName)
## test
add a test for H2, and test inlocaly for mysql

### CODE REVIEW

**Review by seratch — APPROVED** [review]
Thanks for sending this PR. It looks good to me. Once the CI builds pass, we will merge it.

**Review by seratch — CHANGES_REQUESTED** [review]
Can you apply code formatter?

```
[error] scalafmt: 1 files must be formatted (/home/runner/work/scalikejdbc/scalikejdbc/scalikejdbc-mapper-generator-core)
[error] scalafmt: 1 files must be formatted (/home/runner/work/scalikejdbc/scalikejdbc/scalikejdbc-mapper-generator-core)
[error] (mapper-generator-core / Test / scalafmtCheck) scalafmt: 1 files must be formatted (/home/runner/work/scalikejdbc/scalikejdbc/scalikejdbc-mapper-generator-core)
[error] (mapper-generator-core / Compile / scalafmtCheck) scalafmt: 1 files must be formatted (/home/runner/work/scalikejdbc/scalikejdbc/scalikejdbc-mapper-generator-core)
```

**Comment by seratch** [comment]
Can you check the test failures? You change might break the behavior with other RDBMSs.

**Comment by laglangyue** [comment]
yes,I am doing it.

> Can you check the test failures? You change might break the behavior with other RDBMSs.

**Comment by laglangyue** [comment]
This test method depends on the previous testing method to create tables.
`5` should not fixed, but no need to make this change at the moment. Just add the test in the end 
```scala
it should "work fine for all tables defined above" in {
    val allTables = Model(url, username, password).allTables(null)
    allTables should have size 5
```

**Comment by seratch** [comment]
Can you format the code again?

**Comment by laglangyue** [comment]
had used `sbt "+ scalafmtAll" scalafmtSbt` to format.
BTW, @seratch Can you use SBT 1.9.8 for this project? I cannot use it，and SBT-1.9.7 is ok. I have already reported to SBT

**Review by seratch — APPROVED** [review]
Thanks for working on this

**Comment by seratch** [comment]
> Can you use SBT 1.9.8 for this project? I cannot use it，and SBT-1.9.7 is ok. I have already reported to SBT

I am checking this PR using GitHub website, so I am not sure if the issue can arise for me. I'll check if there is such an issue when making a new release within a few days.

**Pull request merged**
