### PR TITLE
Migrate Skinny ORM as scalikejdbc-orm

### PR DESCRIPTION
**Pull request by seratch**
This pull request migrates the Skinny ORM library to this project. 

```scala
import scalikejdbc._
import scalikejdbc.orm.{ CRUDMapper, NoIdCRUDMapper }

// database connection pool
Class.forName("org.h2.Driver")
ConnectionPool.singleton("jdbc:h2:mem:test;MODE=PostgreSQL", "sa", "sa")

// entities
case class Person(id: Int, name: String)
case class Company(id: Int, name: String)
case class Employee(
  companyId: Int,
  personId: Int,
  role: Option[String],
  company: Option[Company] = None,
  person: Option[Person] = None
)

// data mappers
object Person extends CRUDMapper[Person] {
  override lazy val defaultAlias = createAlias("p")
  override def extract(rs: WrappedResultSet, rn: ResultName[Person]) = autoConstruct(rs, rn)
}

object Company extends CRUDMapper[Company] {
  override lazy val defaultAlias = createAlias("c")
  override def extract(rs: WrappedResultSet, rn: ResultName[Company]) = autoConstruct(rs, rn)
}

object Employee extends NoIdCRUDMapper[Employee] {
  override lazy val defaultAlias = createAlias("e")
  override def extract(rs: WrappedResultSet, rn: ResultName[Employee]) = autoConstruct(rs, rn, "company", "person")

  lazy val personRef = belongsTo[Person](Person, (e, p) => e.copy(person = p))
  lazy val companyRef = belongsTo[Company](Company, (e, c) => e.copy(company = c))
  lazy val hasOneRef = hasOne[Company](Company, (e, c) => e.copy(company = c))
  lazy val withAssociations = joins(companyRef, personRef)
}

// examples
val p1 = Person.createWithAttributes("name" -> "Alice")
val p2 = Person.createWithAttributes("name" -> "Bob")
val p3 = Person.createWithAttributes("name" -> "Chris")
val c1 = Company.createWithAttributes("name" -> "Google")
val e1 = Employee.createWithAttributes("companyId" -> c1, "personId" -> p1)
val e2 = Employee.createWithAttributes("companyId" -> c1, "personId" -> p2, "role" -> "Engineer")

Employee.findAll().size should equal(2)

val e = Employee.defaultAlias
val employees = Employee.where(sqls.eq(e.companyId, c1)).apply()
employees.size should equal(2)
```

scalikejdbc-orm does not support the following functionalities that Skinny ORM had.

* Seamless integration with Web framework / input validator is not included. That being said, you still can use the strong parameters interface but your app needs to have the adapter with the interface on your own.
* Transaction per request filters for Servlet apps are not included. If you need the filters, you can cut and paste from the skinny-framework project.
* The database migration tool relying on Flyway is no longer included.

The remarkable changes are:

* The base package is from `skinny.orm` to `scalikejdbc.orm`
* The new library supports only Scala 2.13 and Scala 3

Although the structure of the packages and some class/trait names are improved, most application code using the ORM should be the same with the ones using Skinny ORM.

### CODE REVIEW

**Comment by seratch** [comment]
The Scala 3 compilation is still failing. Will check them later

**Comment by seratch** [comment]
The Scala 3 compilation fails even with the latest nightly build (3.0.2-RC1-bin-20210624-ecbe3d2-NIGHTLY). The orm project has 35 errors at first glance (perhaps, we will see more once we've resolved them). I tried to fix the errors by having `asInstanceOf` but it did not help in some. Also, the updated code does not compile in Scala 2.

```
[info] compiling 67 Scala sources to /Users/ksera/github/scalikejdbc/scalikejdbc-orm/target/scala-3.0.2-RC1-bin-20210624-ecbe3d2-NIGHTLY/classes ...
[error] -- [E007] Type Mismatch Error: /Users/ksera/github/scalikejdbc/scalikejdbc-orm/src/main/scala/scalikejdbc/orm/associations/AssociationsFeature.scala:171:19
[error] 171 |      this -> this.defaultAlias,
[error]     |              ^^^^^^^^^^^^^^^^^
[error]     |Found:    scalikejdbc.SyntaxProvider[Entity]
[error]     |Required: scalikejdbc.QuerySQLSyntaxProvider[scalikejdbc.SQLSyntaxSupport[?], ?]
[error] -- [E007] Type Mismatch Error: /Users/ksera/github/scalikejdbc/scalikejdbc-orm/src/main/scala/scalikejdbc/orm/associations/AssociationsFeature.scala:172:21
[error] 172 |      right -> right.defaultAlias,
[error]     |               ^^^^^^^^^^^^^^^^^^
[error]     |Found:    scalikejdbc.SyntaxProvider[right.Entity]
[error]     |Required: scalikejdbc.QuerySQLSyntaxProvider[scalikejdbc.SQLSyntaxSupport[?], ?]
[error] -- [E007] Type Mismatch Error: /Users/ksera/github/scalikejdbc/scalikejdbc-orm/src/main/scala/scalikejdbc/orm/associations/AssociationsFeature.scala:182:19
[error] 182 |      this -> this.defaultAlias,
[error]     |              ^^^^^^^^^^^^^^^^^
[error]     |Found:    scalikejdbc.SyntaxProvider[Entity]
[error]     |Required: scalikejdbc.QuerySQLSyntaxProvider[scalikejdbc.SQLSyntaxSupport[?], ?]
```

I know that using `_` a lot in types is not a common/recommended way in Scala 3. Thus, this issue in Scala 3 may not be resolved on the compiler side in the short term. I will move this pull request to v4.1 milestone.

**Comment by seratch** [comment]
I have been checking this with [the latest NIGHTLY builds](https://search.maven.org/search?q=g:org.scala-lang%20AND%20a:scala3-library_3) but I'm not sure how I can successfully compile this module with Scala 3. If anyone is interested in helping me here, your suggestions would be greatly appreciated.

**Comment by timzaak** [comment]
I open an issue at https://github.com/lampepfl/dotty/issues/15978.
Maybe need to rewrite `AssociationsFeature.scala`

**Comment by timzaak** [comment]
I tried to change 
`def createJoinDefinition( joinType: JoinType,left: (AssociationsFeature[_], Alias[_]),right: (AssociationsFeature[_], Alias[_]),on: SQLSyntax)`  
=>
 `def createJoinDefinition[L,R]( joinType: JoinType,left: (AssociationsFeature[L], Alias[L]),right: (AssociationsFeature[R], Alias[R]),on: SQLSyntax)`
 
 Then almost everythings  in this file need to add type.
 Even `def joinDefinitions: mutable.LinkedHashSet[JoinDefinition[_]]` in `Associations.scala` would be a problem.
 
`scalikejdbc.orm.associations` may need to be rewrited for Scala3.

**Comment by jchyb** [comment]
Hello! I tried to fix the issues here and came up with this: https://github.com/seratch/scalikejdbc/pull/2 . I believe this should unblock the CI. I tried to keep the changes there at a minimum, however the problematic methods did have to have the type parameters added, like in @timzaak's reply. With that said I do not think there will be any source incompatibilities added by this change with the old ORM (the type inferer should put the correct types there without requiring any additional user action when migrating to this version of ORM)

**Comment by seratch** [comment]
@jchyb Thank you so much for the contribution! FINALLY, this PR compiles and its tests pass. I will merge this PR soon and include the new module in the next minor release 🚀

**Pull request merged**
