### PR TITLE
Fix: Avoid postfixOps in code generator

### LINKED ISSUE #1234: avoid `postfixOps` in code generator
```
[error] -- Error: /tmp/sbt_e60b88db/src/test/scala/app/models/ProgrammersSpec.scala:41:14 
[info] [error] 41 |      created should not beNull
[info] [error]    |      ^^^^^^^^^^^^^^^^^^
[info] [error]    |postfix operator `beNull` needs to be enabled
[info] [error]    |by making the implicit value scala.language.postfixOps visible.
[info] [error]    |----
[info] [error]    |This can be achieved by adding the import clause 'import scala.language.postfixOps'
[info] [error]    |or by setting the compiler option -language:postfixOps.
[info] [error]    |See the Scaladoc for value scala.language.postfixOps for a discussion
[info] [error]    |why the feature needs to be explicitly enabled.
```

https://github.com/scalikejdbc/scalikejdbc/blob/64d995f0a4f80f07b4adeb33e2a667ecb510a4db/scalikejdbc-mapper-generator-core/src/main/scala/scalikejdbc/mapper/CodeGenerator.scala#L917

### PR DESCRIPTION
**Pull request by RhnSharma**
Fixes #1234
Hi @seratch, how does this look?
Let me know if this needs any changes.
Thanks

### CODE REVIEW

**Review by xuwei-k — CHANGES_REQUESTED** [review]
There is no meaning here

**Comment by RhnSharma** [comment]
@xuwei-k Could you please guide me on what changes to be made?
Thanks

**Comment by seratch** [comment]
Hey @RhnSharma, thanks for trying to fix the issue! However, the issue is that we want to improve the generated code, not the code generator itself.

**Comment by RhnSharma** [comment]
@seratch My bad! I misunderstood the issue.

**Pull request closed without merging**
