### PR TITLE
fix parameters passed to TableAsAliasSQLSyntax to rawParameters closes #599

### LINKED ISSUE #599: Can not use ParameterBinder with subQuery
https://github.com/scalikejdbc/scalikejdbc/blob/master/scalikejdbc-interpolation/src/main/scala/scalikejdbc/QueryDSLFeature.scala#L313

### PR DESCRIPTION
**Pull request by takayahilton**

### CODE REVIEW

**Comment by xuwei-k** [comment]
could you write tests?

**Comment by takayahilton** [comment]
where should i write tests?

**Comment by xuwei-k** [comment]
I think here https://github.com/scalikejdbc/scalikejdbc/blob/69bcce0b2/scalikejdbc-interpolation/src/test/scala/scalikejdbc/QueryInterfaceSpec.scala

**Comment by seratch** [comment]
Thanks for the fix 👍

**Pull request merged**
