### PR TITLE
2.4.x: backporting #643

### PR DESCRIPTION
**Pull request by kamekoopa**
backport of #643 to 2.4.x

### CODE REVIEW

**Comment by seratch** [comment]
Thank you for your contribution. I'm willing to publish 2.4.x with this backport. However, this pull request looks still conflicting. Would you please check it out?

**Comment by kamekoopa** [comment]
I was not sure Which branch I should send a PR because contribution.md said "should send PR into master".
@xuwei-k Thank you for your help!

**Comment by seratch** [comment]
Ah, sorry, I missed the target branch was not correct. Thanks!

**Comment by seratch** [comment]
version 2.4.3 is out. https://oss.sonatype.org/content/repositories/releases/org/scalikejdbc/scalikejdbc-core_2.11/2.4.3/

**Pull request merged**
